# Generated by Django 3.0.6 on 2021-08-17 10:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliothecaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_naissance', models.DateField(default=datetime.datetime.now)),
                ('matricule', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.IntegerField()),
                ('titre', models.CharField(max_length=20)),
                ('couverture', models.ImageField(upload_to='livres/couverture')),
                ('pdf', models.FileField(upload_to='livres/pdf')),
                ('annee_publication', models.DateField()),
                ('langue', models.CharField(max_length=50)),
                ('nombre_exemplaire', models.IntegerField()),
                ('prix', models.FloatField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliothequeApi.Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('montant', models.FloatField()),
                ('paiement', models.IntegerField(choices=[(-1, 'Null'), (1, 'Lumicash'), (2, 'Ecocash'), (3, 'Paypal')], default=-1)),
                ('code_transaction', models.PositiveIntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vente_client', to='bibliothequeApi.Client')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livre_vente', to='bibliothequeApi.Livre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vente_bibliothecaire', to='bibliothequeApi.Bibliothecaire')),
            ],
        ),
        migrations.CreateModel(
            name='MesLivre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meslivre_user', to='bibliothequeApi.Client')),
                ('livres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliothequeApi.Livre')),
            ],
        ),
    ]
