# Generated by Django 3.2.6 on 2021-08-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothequeApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliothecaire',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='livre',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='meslivre',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
